In [5]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==7)
print(x)

(array([3]),)


In [7]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr%3==1)
print(x)

(array([0, 3, 5]),)


In [12]:
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,8,side='right')
print(x)

6


In [13]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))

[2 4 5 6 7 9]


In [15]:
import numpy as np
arr=np.array([[7,4,9],[9,1,4]])
print(np.sort(arr))

[[4 7 9]
 [1 4 9]]


In [18]:
import numpy as np
arr=np.array([31,78,69,100])
x=[False,True,False,True]
newarr=arr[x]
print(x)
print(newarr)

[False, False, False, False]
[]


In [19]:
import numpy as np
arr=np.array([31,78,69,100])
filter_arr=arr>70
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True]
[ 78 100]
