In [9]:
import numpy as np
josh=np.random.random((3,4))
print(josh)

[[0.16484419 0.91730218 0.62152228 0.60792176]
 [0.09935802 0.42318826 0.73215717 0.01437961]
 [0.1523125  0.63224521 0.37340055 0.34119355]]


In [8]:
import numpy as np
joshua=np.zeros((3,4))
print(joshua)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
import numpy as np
jos=np.arange(5,30,2)
print(jos)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [10]:
import numpy as np
jo=np.array([[3,4],[4,5]])
print("Dimension",jo.ndim)
print("shape",jo.shape)
print("datatype",jo.dtype)

Dimension 2
shape (2, 2)
datatype int64


In [11]:
j=jo.flatten()
print(j)

[3 4 4 5]
